In [1]:
import pandas as pd
import numpy as np
import data_work

data=pd.read_csv("iotid20_processed.csv")
data

,Target,Src_Port,Dst_Port,Protocol,Flow_Duration,Tot_Fwd_Pkts,Tot_Bwd_Pkts,TotLen_Fwd_Pkts,TotLen_Bwd_Pkts,Fwd_Pkt_Len_Max,...,Init_Bwd_Win_Byts,Fwd_Act_Data_Pkts,Active_Mean,Active_Std,Active_Max,Active_Min,Idle_Mean,Idle_Std,Idle_Max,Idle_Min
0,2,9826,9,1,88,0,1,0,1687,0,...,176,0,0,0,0,0,4719,0,87,87
1,2,11192,74,2,18,16,0,483,25,28,...,0,16,189,417,3,1,33,44,2,1
2,0,2999,10,1,5838,0,2,0,0,0,...,2341,0,0,0,0,0,10579,0,4583,4583
3,1,11060,9,1,118,1,0,0,18,0,...,534,0,0,0,0,0,0,0,0,0
4,2,11185,74,2,28,8,0,238,25,28,...,0,8,0,0,0,0,708,313,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261533,0,2311,10,1,3071,0,1,0,0,0,...,2341,0,0,0,0,0,8335,0,2630,2630
261534,2,4,276,1,242,2,0,1754,1126,1151,...,187,2,0,0,0,0,5048,6817,126,114
261535,2,10851,67,2,14,2,0,59,25,28,...,0,2,0,0,0,0,1823,5903,10,2
261536,2,4786,4,1,234,1,0,17,0,17,...,191,1,0,0,0,0,5504,0,233,233
261537,0,6965,10,1,5399,0,1,0,0,0,...,2341,0,0,0,0,0,11003,0,4958,4956

In [2]:
data_work.count_label_data(data["Target"])

Counter({2: 143328, 0: 59362, 3: 27530, 4: 16274, 1: 15044})

In [3]:
from sklearn.model_selection import train_test_split 
import torch
traindata,test_data=train_test_split(data,test_size=0.4,random_state=42,stratify=data['Target'])
data = traindata.reset_index(drop=True)
test_data = test_data.sample(frac=1).reset_index(drop=True)
client_data,server_data=train_test_split(traindata,test_size=0.03,random_state=22520540,stratify=data['Target'])
client_data = client_data.sample(frac=1).reset_index(drop=True)
server_data = server_data.sample(frac=1).reset_index(drop=True)
print(f"server data quantity {len(server_data)}")
trainloaders,testloaders=data_work.data_split(client_data,"Target", 16,0.01,False)

server data quantity 4708
prepairing non IID dataset
len of client data :152208, len of each subdata : 9513
client number 1 : train(9418), val(95)
client number 2 : train(9418), val(95)
client number 3 : train(9418), val(95)
client number 4 : train(9418), val(95)
client number 5 : train(9418), val(95)
client number 6 : train(9418), val(95)
client number 7 : train(9418), val(95)
client number 8 : train(9418), val(95)
client number 9 : train(9418), val(95)
client number 10 : train(9418), val(95)
client number 11 : train(9418), val(95)
client number 12 : train(9418), val(95)
client number 13 : train(9418), val(95)
client number 14 : train(9418), val(95)
client number 15 : train(9418), val(95)
client number 16 : train(9418), val(95)

In [4]:
server_data.to_csv("./dataset/server_data.csv")
test_data.to_csv("./dataset/test_data.csv")
for i in range(16):
    trainloaders[i] = trainloaders[i].sample(frac=1).reset_index(drop=True)
    trainloaders[i].to_csv(f"./dataset/trainloader_{i}.csv")
    testloaders[i]= testloaders[i].sample(frac=1).reset_index(drop=True)
    testloaders[i].to_csv(f"./dataset/testloader_{i}.csv")

In [5]:
len(server_data)

4708

In [6]:
te=pd.read_csv("./dataset/trainloader_9.csv", index_col=0)

In [7]:
te

,Target,Src_Port,Dst_Port,Protocol,Flow_Duration,Tot_Fwd_Pkts,Tot_Bwd_Pkts,TotLen_Fwd_Pkts,TotLen_Bwd_Pkts,Fwd_Pkt_Len_Max,...,Init_Bwd_Win_Byts,Fwd_Act_Data_Pkts,Active_Mean,Active_Std,Active_Max,Active_Min,Idle_Mean,Idle_Std,Idle_Max,Idle_Min
0,2,9300,9,1,121,0,1,0,1791,0,...,52,0,0,0,0,0,5048,0,120,120
1,2,8011,70,1,121,1,0,0,0,0,...,3203,0,0,0,0,0,5048,0,120,120
2,2,11185,74,2,13,6,0,175,25,28,...,0,6,227,0,2,2,385,625,3,1
3,2,8006,76,2,238,2,0,1750,14,1148,...,0,2,0,0,0,0,5034,0,118,118
4,2,9732,67,2,29,2,0,59,25,28,...,0,2,0,0,0,0,2906,7805,23,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9413,2,8014,70,1,161,2,0,0,0,0,...,3203,0,0,0,0,0,4621,6627,85,74
9414,2,8543,9,1,82,0,1,0,1790,0,...,2458,0,0,0,0,0,4638,0,81,81
9415,2,10325,70,1,79,0,1,0,1878,0,...,748,0,0,0,0,0,4609,0,78,78
9416,2,10368,76,2,288,3,0,2180,1119,1148,...,0,3,0,0,0,0,4821,12268,137,72
9417,2,11186,74,2,271,16,0,483,25,28,...,0,16,0,0,0,0,3129,12573,160,2

In [18]:
te=pd.read_csv("./data/trainloader_9.csv", index_col=0)

In [19]:
te

,subcategory,pkSeqID,stime,flgs,proto,saddr,sport,daddr,dport,pkts,...,max,spkts,dpkts,sbytes,dbytes,rate,srate,drate,attack,category
0,5,15713,14548,0,5,7,50692,34,6889,1,...,122,0,1,1,2,58915,0,0,1,3
1,5,9473,8526,0,1,10,5,28,258,0,...,0,0,0,6,0,0,0,0,1,3
2,5,18446,16842,0,5,5,45878,34,2623,1,...,108,0,1,1,2,58969,0,0,1,3
3,5,30543,28204,0,5,6,14179,34,6855,3,...,5158,1,2,41,14,55711,44641,36765,1,3
4,5,26598,24951,0,5,5,15885,34,1212,1,...,67,0,1,1,2,59176,0,0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9380,5,29643,27568,0,5,8,15683,34,7112,2,...,5140,1,1,41,2,54528,44657,0,1,3
9381,5,43908,39397,0,1,13,5,30,1096,0,...,0,0,0,6,0,0,0,0,1,3
9382,5,9654,8707,0,1,10,5,28,924,0,...,0,0,0,6,0,0,0,0,1,3
9383,6,253920,204540,10,5,6,7338,34,6775,1,...,0,1,0,121,0,3670,5719,0,1,0
9384,6,218139,169510,8,5,5,58000,34,6775,5,...,29480,3,2,174,14,31803,27144,7235,1,0

In [4]:
import sys
sys.path.append("DL_model_batch.py")